sudo: required
language: python
python: '3.6'
install:
- python setup.py install
before_script:
- pip install --upgrade pip
- pip install codecov
- pip install coveralls
- pip install pandas
- pip install greek-accentuation
- pip install fuzzywuzzy
- pip install python-Levenshtein
- pip install gensim
script:
- nosetests --no-skip --with-coverage --cover-package=cltk --with-doctest
after_success:
- codecov
- python cltk/utils/contributors.py
- pip list > requirements.txt
- git add contributors.md
- git add requirements.txt
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iUwU43gmMlVDNe7/vKaBsY8yjcOLLpakM/DLfSxszBQWm3cwciWT2xa33pE3ViStvoP5E0VBEuXDDzaC3hu+aHnMaMyih7EnoEF9Za9WBAmaCv/jzUt9aJdk06KAXK7JIYOEKAw1CQkypYGP96ehqRJ73q3MlWA+YULxJZKEt1M=
  file: contributors.md
  on:
    repo: cltk/cltk
    branch: push-test
# https://docs.travis-ci.com/user/deployment/#Deploying-to-Multiple-Providers